"""Adds models for defining Feature types and Cluster model features

Revision ID: 37072281c42b
Revises: 6fc47f0a55aa
Create Date: 2022-10-03 06:55:34.776772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '37072281c42b'
down_revision = '6fc47f0a55aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_model_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_model_features_cluster_id'), 'cluster_model_features', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_model_features_id'), 'cluster_model_features', ['id'], unique=False)
    op.create_table('feature_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_feature_options_cluster_id'), 'feature_options', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_feature_options_id'), 'feature_options', ['id'], unique=False)

    feature_type_enum = postgresql.ENUM('DECIMAL', 'INTEGER', 'CATEGORICAL', 'TEXT', 'DATE', 'URL', 'BOOLEAN', 'UNKNOWN', name='featuretype')
    feature_type_enum.create(op.get_bind())
    op.add_column('features', sa.Column('type', feature_type_enum, server_default='UNKNOWN', nullable=False))
    op.add_column('features', sa.Column('number_of_decimals', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'number_of_decimals')
    op.drop_column('features', 'type')
    op.drop_index(op.f('ix_feature_options_id'), table_name='feature_options')
    op.drop_index(op.f('ix_feature_options_cluster_id'), table_name='feature_options')
    op.drop_table('feature_options')
    op.drop_index(op.f('ix_cluster_model_features_id'), table_name='cluster_model_features')
    op.drop_index(op.f('ix_cluster_model_features_cluster_id'), table_name='cluster_model_features')
    op.drop_table('cluster_model_features')
    # ### end Alembic commands ###
