"""Adds unique constraint to feature_options table

Revision ID: 41faf152923d
Revises: 52dc806bacef
Create Date: 2022-10-06 12:12:13.736900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41faf152923d'
down_revision = '52dc806bacef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feature_options_value_key', 'feature_options', type_='unique')
    op.create_unique_constraint('unique_option_per_feature', 'feature_options', ['feature_id', 'value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_option_per_feature', 'feature_options', type_='unique')
    op.create_unique_constraint('feature_options_value_key', 'feature_options', ['value'])
    # ### end Alembic commands ###
