"""Adds code column to Feature table

Revision ID: 5e6e0577205d
Revises: d3a641e0638c
Create Date: 2022-10-24 09:44:20.023969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6e0577205d'
down_revision = 'd3a641e0638c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'features', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'features', type_='unique')
    op.drop_column('features', 'code')
    # ### end Alembic commands ###
