"""Adds cascade option to usecluster model

Revision ID: 6fc47f0a55aa
Revises: 4ed0f61749fb
Create Date: 2022-09-25 19:29:15.363994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc47f0a55aa'
down_revision = '4ed0f61749fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_clusters_user_id_fkey', 'user_clusters', type_='foreignkey')
    op.create_foreign_key(None, 'user_clusters', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_clusters', type_='foreignkey')
    op.create_foreign_key('user_clusters_user_id_fkey', 'user_clusters', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
