"""Adds ExportFile model

Revision ID: c7ad5e3cc0e3
Revises: 5e6e0577205d
Create Date: 2022-10-25 13:03:36.301836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ad5e3cc0e3'
down_revision = '6efc92db4e2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_files_id'), 'export_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_files_id'), table_name='export_files')
    op.drop_table('export_files')
    # ### end Alembic commands ###
