"""Adds is_propertyset_feature column to Feature model

Revision ID: d3a641e0638c
Revises: 41faf152923d
Create Date: 2022-10-19 10:46:31.699619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a641e0638c'
down_revision = '41faf152923d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('is_propertyset_feature', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'is_propertyset_feature')
    # ### end Alembic commands ###
