version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/postgres'
      
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=sqs
    ports:
      - "4566:4566"
    command: --output json

    