version: '3'
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./app.env
      
  db:
    image: postgres
    restart: always
    env_file:
      - ./db/db.env
    ports:
      - "5433:5432"
  localstack:
    image: localstack/localstack
    container_name: localstack
    depends_on:
      - app
    environment:
      - SERVICES=sqs
    ports:
      - "4566:4566"
    command: --output json
    env_file:
      - ./sqs.env

    